version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: &api-environment
      FLASK_SECRET_KEY: secret_key
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      FLASK_DEBUG: 1
      FLASK_APP: prototype_it2002/app.py
    env_file:
      - .env
      
    command: poetry run flask run --host=0.0.0.0 --port=8000

  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres